# Get user wrong id request
GET http://localhost:8000/users/asdasdasd
Content-Type: application/json

{}

###

# Get user with valid id that doesn't exist
GET http://localhost:8000/users/1024242
Content-Type: application/json

{}

###

# Get user with valid id that exists
GET http://localhost:8000/users/1
Content-Type: application/json

{}

###

# Get user with valid id that exists with X-Public header
GET http://localhost:8000/users/1
Content-Type: application/json
X-Public: true

{}

###